server:
  port: 9999

database:
  url: jdbc:mysql://localhost:3306/aiphoto?useUnicode=true&characterEncoding=utf8&useSSL=false
  username: root
  password: 123456

AIFace:
  url: https://api-wuxi-1.cmecloud.cn:8443/api/imagerecog/china_mobile/engine/image/generalImageDetect
  AK: 02e07647f119456f9c4244024a0096c2
  SK: a0a78d491dbe447d82f4a0a683e23353
  confidence: 0.85
  reConfidence: 0.60
  myurl: http://192.168.43.184:8899/imgCfy

